
- name: Installing python 3 
  ansible.builtin.package:
    name: 
        - python36
        - gcc 
        - python3-devel
    state: present   


- name: create roboshop user account
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user


- name: Download and extract
  ansible.builtin.include_role:
    name: common
    tasks_from: download


- name: Cleanup old content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: copy file to destination 
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop


- name: Install requrement, using the 'pip3' executable
  ansible.builtin.pip:
    name: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Creating the package
  ansible.builtin.shell: pip3 install -r   
  args:
    chdir: 
  become_user: roboshop

- name: Payment ini file change
  ansible.builtin.shell: 
   - USERID=$(id -u roboshop)
   - GROUPID=$(id -g roboshop)
   - sed -i -e "/^uid/ c uid=$USERID"  -e "/^gid/ c gid=$GROUPID" /home/$APPUSER/$COMPONENT/$COMPONENT.ini
  become_user: roboshop




# - name: Updating {{COMPONENT}} Config
#   ansible.builtin.replace:
#     path: /etc/{{COMPONENT}}/{{COMPONENT}}.conf
#     regexp: '127.0.0.1'
#     replace: '0.0.0.0'

- name: Configure services
  ansible.builtin.include_role:
    name: common
    tasks_from: configuringservice