- name: set hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}


- name: Copy redis repo 
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo


- name: Installing mongodb-org  
  ansible.builtin.package:
    name: redis-6.2.7  
    state: present 

- name: Updating Redis Config
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis
  ansible.builtin.service:
    name: redis
    state: started         
    enabled: yes