- name: Install ntpdate
  ansible.builtin.package:
    name: nginx
    state: present

- name: Download and extract frontend
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /temp
    remote_src: yes

- name: Cleanup FOlder containt 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: copy file frontend containt to nginx path 
  ansible.builtin.copy: 
    src: /temp/frontend.main/static/
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy roboshop configuration
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Restart service nginx 
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes


