- name: check tomcat is running or not
  hosts: all
  tasks: 
    - name: check tomcat is running or not
      ansible.builtin.shell: ps -ef | grep java | grep -v grep
      register: out
      ignore_errors: yes
    -name: Print out
      ansible.builtin.debug:
        msg: Start Tomcat
    -name: Print out
      ansible.builtin.debug:
        msg: "{{out.stdout}}"