- name: Set Hostname
  ansible.builtin.include_role:
    name: common
    tasks_from: sethostname 

# just to test main branch and other branch

- name: Configuring {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs 
