- name: Configure yum repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | bash

- name: Installing NodeJS 
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop:
      - nodejs
      - gcc-c++

- name: Add the user
  ansible.builtin.user:
    name: roboshop
    comment: roboshop project app user


- name: Download and extract
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Cleanup old content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: copy file to destination 
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop

- name: Installing node.js package.
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}


- name: Copy file from Destination 
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restarting Service 
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true 
    name: "{{COMPONENT}}"
    enabled: yes
