- name: Configure yum repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | bash

- name: Installing Nodejs
  ansible.builtin.packge:
    name: "{{item}}"
    state: present
  loop:
      - nodejs
      - gcc-c++

- name: Add the user
  ansible.builtin.user:
    name: roboshop
    comment: roboshop project app user


- name: Download and extract
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Cleanup old content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: copy file to destination 
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop